repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
      - id: black
        args: ['.']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
        - --max-line-length=120

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
